/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/capture-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Capture Event */
        post: operations["capture_event_api_capture_events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_capture_event_api_capture_events_post */
        Body_capture_event_api_capture_events_post: {
            /** Manifest */
            manifest: string;
            /** Files */
            files: string[];
        };
        /** CaptureEventResponse */
        CaptureEventResponse: {
            /** Event Id */
            event_id: string;
            /** Stored Items */
            stored_items: components["schemas"]["StoredItemResponse"][];
        };
        /** CaptureItem */
        CaptureItem: {
            /** Slot */
            slot: number;
            /** Payload Index */
            payload_index: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "string" | "file";
            /** Mime Type */
            mime_type?: string | null;
            /** Original Name */
            original_name?: string | null;
            /** Original Relative Path */
            original_relative_path?: string | null;
            /** Text Format */
            text_format?: string | null;
            /** Size */
            size?: number | null;
        };
        /** CaptureManifest */
        CaptureManifest: {
            /**
             * Source
             * @enum {string}
             */
            source: "paste" | "drop" | "typed";
            /** Items */
            items: components["schemas"]["CaptureItem"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** StoredItemResponse */
        StoredItemResponse: {
            /** Stored Path */
            stored_path: string;
            /** Metadata Path */
            metadata_path: string;
            /** Original Name */
            original_name?: string | null;
            /** Original Relative Path */
            original_relative_path?: string | null;
            /** Mime Type */
            mime_type?: string | null;
            /** Size */
            size: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    capture_event_api_capture_events_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_capture_event_api_capture_events_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptureEventResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
